apiVersion: v1
appVersion: 0.8.0
description: KubeDB by AppsCode - Production ready databases on Kubernetes
home: https://github.com/kubedb/cli
icon: https://cdn.appscode.com/images/icon/kubedb.png
maintainers:
- email: kubedb@appscode.com
  name: appscode
name: kubedb
sources:
- https://github.com/kubedb/cli
version: 0.8.0
