FROM postgres:11-beta3-alpine
ENV POSTGRES_USER damienbod
ENV POSTGRES_PASSWORD damienbod
ENV POSTGRES_DB damienbod
#COPY dbscripts/10-init.sql /docker-entrypoint-initdb.d/10-init.sql
#COPY dbscripts/20-damienbod.sql /docker-entrypoint-initdb.d/20-database.sql